### ISSUE TITLE
HTML Coding is Unfunctional

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Cheter-IDE#1]
When you try to type the following code (as an example):
```html
<h1> </h1>
```
It gives you this instead:
![Screenshot of Issue](https://user-images.githubusercontent.com/30969346/43933583-43401500-9bff-11e8-871a-866f4ae490a4.png).

Could be the monospace font?

**Comment by ialoam** [comment]
ill look

**Comment by Incrested** [comment]
Kudos; push it to the repo locally if you find one please; then close this with the commit (short) hash here

**Comment by ialoam** [comment]
Here are a few ones i saw:

https://fonts.google.com/specimen/Ubuntu+Mono

https://fonts.google.com/specimen/Cousine

https://fonts.google.com/specimen/Overpass+Mono

https://fonts.google.com/specimen/Share+Tech+Mono

**Comment by Incrested** [comment]
I think Ubuntu Mono would be the best bet; I can add it in a bit unless you want to yourself

**Comment by Incrested** [comment]
Fixed Here: 30e926381d591c26927c14d76a49df8b220ef4fa
