### ISSUE TITLE
Save to File

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Cheter-IDE#3]
We need to find a way to save to file using Electron/Node. It needs to be able to save virtually every format (.vb, .js, .css, .etc)

**Comment by ialoam** [comment]
well make a way to open files you select and just write your contents when saved

**Comment by Incrested** [comment]
Yeah, I meant as a milestone for this in a sense. I was mostly thinking something such as [FileSaver](https://github.com/eligrey/FileSaver.js)

**Comment by ialoam** [comment]
well then use that

**Comment by Incrested** [comment]
Lol ik; again: mostly using this for milestones so it's easy to collaborate with stuff like this.

**Comment by Incrested** [comment]
I'm currently adding in FS: Chrome has a blob cap of 500MiB (~524MB); so until needed: this should work. Should be done later today or early tomorrow.

**Comment by Incrested** [comment]
Added feature in c8411d8 with a file cap of ~500MiB without the need of extra dependencies™
